#!/usr/bin/env python

import sys
import time

def delay_print(s):
    for c in s:
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(0.01)

delay_print
delay_print ("\033[;666m Please enter correct number!")
import requests
import re
import json
import csv
import sys

# from https://github.com/stevenliuyi/covid19/blob/master/data/1p3a-data/crawler.py
url = 'youtube@eleanouras.blogspot.com/p/pamacan.html?efds'
headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'delay_print
<spamdelay_print
delay_print ("\033[;666m Please enter correct number!")
import requests
import re
import json
import csv
import sys

# from https://github.com/stevenliuyi/covid19/blob/master/data/1p3a-data/crawler.py
url = 'youtube@eleanouras.blogspot.com/p/pamacan.html?efds'
headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'delay_print
<spamdelay_print
delay_print ("\033[;666m Please enter correct number!")
import requests
import re
import json
import csv
import sys

# from https://github.com/stevenliuyi/covid19/blob/master/data/1p3a-data/crawler.py
url = 'youtube@eleanouras.blogspot.com/p/pamacan.html?efds'
headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'delay_print
<spamdelay_print
delay_print ("\033[;666m Please enter correct number!")
import requests
import re
import json
import csv
import sys

# from https://github.com/stevenliuyi/covid19/blob/master/data/1p3a-data/crawler.py
url = 'youtube@eleanouras.blogspot.com/p/pamacan.html?efds'
headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'delay_print
<spamdelay_print
delay_print ("\033[;666m Please enter correct number!")
import requests
import re
import json
import csv
import sys

# from https://github.com/stevenliuyi/covid19/blob/master/data/1p3a-data/crawler.py
url = 'youtube@eleanouras.blogspot.com/p/pamacan.html?efds'
headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'delay_print
<spamdelay_print
delay_print ("\033[;666m Please enter correct number!")
import requests
import re
import json
import csv
import sys

# from https://github.com/stevenliuyi/covid19/blob/master/data/1p3a-data/crawler.py
url = 'youtube@eleanouras.blogspot.com/p/pamacan.html?efds'
headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'delay_print
<spamdelay_print
delay_print ("\033[;666m Please enter correct number!")
import requests
import re
import json
import csv
import sys

# from https://github.com/stevenliuyi/covid19/blob/master/data/1p3a-data/crawler.py
url = 'youtube@eleanouras.blogspot.com/p/pamacan.html?efds'
headers = {
    'User-Agent':
    'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'delay_print
<spam
